services:
  db:
    image: postgres:16-alpine
    container_name: car_service_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: car_service_db
    ports:
      - '5434:5432' 
    volumes:
      - devdb_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  devdb_data:
